version: '3'
services:
  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile.ffmpeg
    user: root
    volumes:
      - .:/app
    command: ["-y", "-stream_loop", "-1", "-i", "/app/1.mp4", "-i", "/app/1.wav", "-map", "0:v", "-map", "1:a", "-c:v", "libx264", "-c:a", "aac", "-vf", "subtitles=/app/output.srt:force_style='FontName=Noto Sans CJK SC'", "-shortest", "/app/output.mp4"]