version: '3'
services:
  yt-dlp:
    image: jauderho/yt-dlp
    volumes:
      - ../../novel/output:/app
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 1000; done"]
    # command: ["yt-dlp", "--no-playlist", "-f", "bestvideo[ext=mp4]/best[ext=mp4]", "-o", "/app/video-%(id)s.%(ext)s", "https://www.youtube.com/watch?v=YHU0aM9rCFA"]
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890